name: "Release"

on:
  release:
    types:
      - published

jobs:
  release-phar:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
        php-versions:
          - '8.1'
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          tools: composer, box
          php-version: "${{ matrix.php-version }}"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ramsey/composer-install@v3
      - name: Build PHAR
        run: box compile
      - name: Check the PHAR executes
        run: php pie.phar --version
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_SIGNING_KEY }}
          passphrase: ${{ secrets.GPG_SIGNING_KEY_PASSPHRASE }}
      - name: Sign the PHAR
        run: |
          gpg --local-user asgrim+pie-releases@php.net \
              --batch \
              --yes \
              --passphrase="${{ secrets.GPG_SIGNING_KEY_PASSPHRASE }}" \
              --detach-sign \
              --output pie.phar.asc \
              pie.phar
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
          files: |
            pie.phar
            pie.phar.asc

  docker-binary-only-image:
    needs: release-phar
    name: Docker binary-only image
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=true
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          target: standalone-binary
          build-args: |
            PIE_VERSION=${{ github.ref_name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
